name: mude
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - dash=2.6.1
  - ipympl=0.9.1
  - jupyter=1.0.0
  - jupyter-dash=0.4.2
  - matplotlib=3.5.2
  - numpy=1.22.3
  - pandas=1.4.3
  - scikit-learn=1.0.2
