name: mude-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ipympl=0.9.1
  - jupyter=1.0.0
  - jupyterlab=3.4.4
  - jupyterlab_vim=0.15.1
  - matplotlib=3.5.2
  - numpy=1.22.3
  - pip
  - scikit-learn=1.0.2
  - spyder=5.2.2
  - pip:
    - nbdime
    - nbmerge
